# Generated by Django 5.0.3 on 2024-03-10 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleregister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='downloadedfile',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='handleregister.processedcompany'),
        ),
        migrations.AlterField(
            model_name='downloadedfile',
            name='file_path',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='processedcompany',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='processedcompany',
            name='search_record',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='handleregister.searchrecord'),
        ),
    ]
